workflows:
  android-workflow:
    name: Build Android APK
    instance_type: mac_mini
    max_build_duration: 10
    environment:
      vars:
        PACKAGE_NAME: "com.example.myapp"
    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
